# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

#dando nome
name: Python application

on:
#criando os eventos para disparar:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
#criando os passo
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
      #indicando a versão do python
        python-version: "3.10"

      #instalando as dependências
    - name: Install dependencies
    #verificando o requirements
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # criando um passo na pipeline para o teste/ para rodar o coverage
    - name: Teste
      run: coverage run -m date_teste

    - name: Relatorio
      run: coverage report
